# FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime
# FROM torch-img
FROM nvcr.io/nvidia/pytorch:24.06-py3

COPY ModeTv2 /workdir/ModeTv2

WORKDIR /workdir/ModeTv2/modet

RUN pip install pystrum natsort
# RUN cd modet && pip install .
RUN pip install scikit-image
RUN pip install .
RUN pip install nibabel


#COPY source source
# Pot do containerja
# WORKDIR /workspace/modetv2
